[project]
name = "cellpack-analysis"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Saurabh Mogre", email = "saurabh.mogre@alleninstitute.org"},
]
dependencies = [
    "aicsimageio>=4.14.0",
    "matplotlib>=3.9.0",
    "numpy>=1.26.4",
    "pacmap>=0.7.2",
    "pandas>=2.2.2",
    "pathlib>=1.0.1",
    "scikit-image>=0.22.0",
    "scikit-learn>=1.5.0",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "tqdm>=4.66.4",
    "trimesh>=4.4.0",
    "ipykernel>=6.29.4",
    "aicsshparam>=0.1.10",
    "pyarrow>=16.1.0",
    "quilt3>=5.4.0",
]
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "Allen Institute Software License"}


[tool.pdm]
distribution = false
