[project]
name = "cellpack-analysis"
description = "Default template for PDM package"
authors = [
    {name = "Saurabh Mogre", email = "saurabh.mogre@alleninstitute.org"},
]
license = {text = "Allen Institute Software License"}
version = "0.1.0"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "aicsimageio>=4.14.0",
    "matplotlib>=3.9.0",
    "numpy>=1.26.4",
    "pacmap>=0.7.2",
    "pandas>=2.2.2",
    "pathlib>=1.0.1",
    "scikit-image>=0.22.0",
    "scikit-learn>=1.5.0",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "tqdm>=4.66.4",
    "trimesh>=4.4.0",
    "ipykernel>=6.29.4",
    "aicsshparam>=0.1.10",
    "pyarrow>=16.1.0",
    "quilt3>=5.4.0",
    "rtree>=1.2.0",
    "python-dotenv>=1.0.1",
    "cellpack @ git+https://github.com/mesoscope/cellpack.git@cellpack-analysis",
    "hydra-core>=1.3.2",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "check-manifest>=0.49",
    "pre-commit>=3.7.1",
]
lint = [
    "black>=24.4.2",
    "isort>=5.13.2",
    "ruff>=0.4.6",
    "mypy>=1.10.0",
]
test = [
    "pytest>=8.2.2",
    "pytest-cov>=5.0.0",
    "pytest-raises>=0.11",
    "coverage>=7.5.3",
]
debug = [
    "ipdb>=0.13.13",
]
docs = [
    "sphinx>=7.3.7",
    "furo>=2024.5.6",
    "myst-parser>=3.0.1",
    "sphinx-copybutton>=0.5.2",
]

[tool.black]
line-length = 88

[tool.isort]
line_length = 88
profile = "black"

# https://github.com/charliermarsh/ruff
[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
extend-select = [
    "E",      # style errors
    "F",      # flakes
    "D",      # pydocstyle
    "I001",   # isort
    "UP",     # pyupgrade
    "N",      # pep8-naming
    # "S",    # bandit
    "C",      # flake8-comprehensions
    "B",      # flake8-bugbear
    "A001",   # flake8-builtins
    "RUF",    # ruff-specific rules
    "RUF100", # Unused noqa directive
]
extend-ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D103", # Missing docstring in public function
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in __init__
    "D202", # Blank lines between the function body and the function docstring
    "D203", # 1 blank line required before class docstring
    "D205", # 1 blank line required between summary line and description
    "D212", # Multi-line docstring summary should start at the first line
    "D213", # Multi-line docstring summary should start at the second line
    "D413", # Missing blank line after last section
    "D416", # Section name should end with a colon
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "aicsshparam.*",
    "aicscytoparam.*",
    "autopack,*",
    "cellpack.*",
    "pacmap.*",
    "pandas.*",
    "quilt3.*",
    "scipy.*",
    "seaborn.*",
    "sklearn.*",
    "tqdm.*",
    "umap.*",
    "vtk.*",
]
ignore_missing_imports = true
